version: "3.8"
services:
  wms-ml-onnx:
    build: .
    container_name: wms-ml-onnx
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - CAMERA_URL_1=${CAMERA_URL_1}
      - CAMERA_URL_2=${CAMERA_URL_2}
    volumes:
      - .:/app
    restart: unless-stopped
