version: "3.8"

services:
  wms-ml-ultralytics:
    build: .
    container_name: wms-ml-ultralytics
    env_file:
      - .env
    environment:
      - YOLO_CONFIG_DIR=/tmp/Ultralytics
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
