version: "3.8"

services:
  wms-ml-ultralytics:
    build: .
    container_name: wms-ml-ultralytics
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - CAMERA_URL_1=${CAMERA_URL_1}
      - CAMERA_URL_2=${CAMERA_URL_2}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
