name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  onnx-model:
    name: ONNX Model Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ONNX]') ||
      contains(github.event.head_commit.message, '[ALL]') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, '[ONNX]') || contains(github.event.pull_request.title, '[ALL]')))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend-ml-system/.onnx
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.onnx
          pytest

  ultralytics-model:
    name: Ultralytics Model Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ULTRALYTICS]') ||
      contains(github.event.head_commit.message, '[ALL]') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, '[ULTRALYTICS]') || contains(github.event.pull_request.title, '[ALL]')))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug - List directory structure
        run: |
          echo "Repository root:"
          ls -la
          echo "Backend-ml-system contents:"
          ls -la backend-ml-system/
          echo "Looking for ultralytics folder..."
          find . -name "*ultralytics*" -type d

      - name: Install dependencies
        run: |
          cd backend-ml-system/.ultralytics
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.ultralytics
          pytest

  video-stream:
    name: Video Stream Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[VIDEO]') ||
      contains(github.event.head_commit.message, '[ALL]') ||
      (github.event_name == 'pull_request' && (contains(github.event.pull_request.title, '[VIDEO]') || contains(github.event.pull_request.title, '[ALL]')))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend-ml-system/.video_stream
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.video_stream
          pytest
