name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  onnx-model:
    name: ONNX Model Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ONNX]') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[ONNX]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend-ml-system/.onnx-model
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.onnx-model
          pytest

  ultralytics-model:
    name: Ultralytics Model Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[ULTRALYTICS]') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[ULTRALYTICS]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend-ml-system/.ultralytics-model
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.ultralytics-model
          pytest

  video-stream:
    name: Video Stream Service
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[VIDEO]') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[VIDEO]'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend-ml-system/.video-stream
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend-ml-system/.video-stream
          pytest
